name: Staging Deployment

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-18.04
    # environment: staging
    steps:

      - name: INSTALL PROJECT DEPENDENCIES (YARN)
        run: echo "${{ github.ref_name }}"